spring.application.name=CalendarX

# SpringDoc /v3/api-docs
springdoc.api-docs.enabled=true
# SpringDoc /swagger-ui.html
springdoc.swagger-ui.enabled=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.prometheus.metrics.export.enabled=true

management.metrics.tags.application=${spring.application.name}
management.metrics.tags.pod=${HOSTNAME}

server.port=8088